services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app
            - .env:/var/www/app/.env
        depends_on:
            - redis
        networks:
            - app

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - app

    db:
        image: mysql:8.0
        platform: linux/x86_64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-app}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3301:3306"
        networks:
            - app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/x86_64
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
        networks:
            - app

    redis:
        image: redis:latest
        restart: unless-stopped
        ports:
            - "6371:6379"
        networks:
            - app

networks:
    app:
        driver: bridge
